workflows:
  - name: n8ntest
    endpoint: /run/n8ntest
    target: http://localhost:5678/webhook-test/n8ntest2
    method: POST
keys:
  - name: Test
    key: wfapi-ZVE3yxiXZ2tB2vBSim3mO8knqiwo6Uw3n7z-swBorxk
    rate_limit_per_minute: 60
    created_at: '2026-04-21'
    expires_at:
    allowed_gateways:
      - n8ntest
logging:
  file: logs/usage.log
stripe:
  webhook_secret:
  api_key:
  price_to_gateway: {}
server:
  host: 0.0.0.0
  port: 8000
